# Generated by Django 4.0.2 on 2022-02-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperBowl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('date_played', models.DateField()),
                ('win_team', models.CharField(max_length=75)),
                ('win_score', models.IntegerField()),
                ('lose_team', models.CharField(max_length=75)),
                ('lose_score', models.IntegerField()),
                ('stadium', models.CharField(max_length=75)),
                ('where', models.CharField(max_length=75)),
                ('mvp', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorldSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_played', models.IntegerField()),
                ('win_team', models.CharField(max_length=75)),
                ('winner_wins', models.IntegerField()),
                ('lose_team', models.CharField(max_length=75)),
                ('loser_wins', models.IntegerField()),
            ],
        ),
    ]
